# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 842bf525eea813b1e21daf3d921c20af9dcc3cfcb2275e2c57cd070c7516671e3b4d0ec6964d525258c82442187e7c901a5f9129f59951c86bcba862fcef3a38

test:
  secret_key_base: 793dfe17c8b36d8aefefe5242951a0ee23c412248e74f0172658ab9e1e869c83f929bcb00cead6639ee8fe5fda7980965acfc5ebc94a861b3dc17d4e2ce85866

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
